albums/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.AlbumView.as_view(), name='index'),
    path('filter/', views.FilterAlbumsView.as_view(), name='filter'),
    path('search/', views.Search.as_view(), name='search'),
    path('add-rating/', views.AddStarRating.as_view(), name='add_rating'),
    path('<slug:slug>/', views.AlbumDetailView.as_view(), name='album_detail'),
    path('review/<int:pk>/', views.AddReview.as_view(), name='add_review'),
    path('artist/<str:slug>/', views.ArtistView.as_view(), name='artist_detail'),
    path('band/<str:slug>/', views.BandView.as_view(), name='band_detail'),
]

music_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', include("contact.urls")),
    path('', include('albums.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

albums/models.py
from django.db import models
from datetime import date

from django.db.models import Avg
from django.urls import reverse


class Band(models.Model):
    name = models.CharField('Группа', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def get_albums(self):
        albums = Album.objects.filter(category=self)
        return albums


class ArtistLabel(models.Model):
    name = models.CharField('Имя', max_length=256)
    description = models.TextField('Описание')
    age = models.PositiveSmallIntegerField('Возраст', default=0)
    image = models.ImageField('Изображение', upload_to='artists_labels/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Музыкант - лейбл'
        verbose_name_plural = 'Музыканты и лейблы'


class Genre(models.Model):
    name = models.CharField('Название', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Album(models.Model):
    title = models.CharField('Название', max_length=256)
    description = models.TextField('Описание')
    cover = models.ImageField('Обложка', upload_to='albums/')
    year = models.PositiveSmallIntegerField('Год выхода')
    country = models.CharField('Страна', max_length=50)
    label = models.ManyToManyField(ArtistLabel, verbose_name='Лейбл', related_name='album_label')
    artist = models.ManyToManyField(ArtistLabel, verbose_name='Музыкант', related_name='album_artist')
    genres = models.ManyToManyField(Genre, verbose_name='Жанры')
    premiere = models.DateField('Дата выхода', default=date.today)
    streams = models.PositiveIntegerField('Прослушиваний', default=0)
    category = models.ForeignKey(Band, verbose_name='Группа', on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=256, unique=True)
    draft = models.BooleanField('Черновик', default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Альбом'
        verbose_name_plural = 'Альбомы'

    def get_absolute_url(self):
        return reverse('album_detail', kwargs={'slug': self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    def average_rating(self):
        reviews = Rating.objects.filter(album=self).aggregate(average=Avg('star'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg


class Images(models.Model):
    title = models.CharField('Заголовок', max_length=100)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='covers/')
    album = models.ForeignKey(Album, verbose_name='Альбом', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'


class RatingStar(models.Model):
    value = models.SmallIntegerField('Значение', default=0)

    def __str__(self):
        return str(self.value)

    class Meta:
        verbose_name = 'Звезда рейтинга'
        verbose_name_plural = 'Звезды рейтинга'
        ordering = ['-value']


class Rating(models.Model):
    ip = models.CharField('IP адрес', max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name='Звезда')
    album = models.ForeignKey(Album, on_delete=models.CASCADE, verbose_name='Альбом')

    def __str__(self):
        return f'{self.star} - {self.album}'

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинги'


class Reviews(models.Model):
    email = models.EmailField()
    name = models.CharField('Имя', max_length=100)
    text = models.TextField('Сообщение', max_length=5000)
    parent = models.ForeignKey('self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True)
    album = models.ForeignKey(Album, verbose_name='Альбом', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} - {self.album}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

albums/forms.py
from django import forms

from .models import Reviews, Rating, RatingStar


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ('name', 'email', 'text')


class RatingForm(forms.ModelForm):
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ('star',)

albums/views.py
from django.db.models import Q, Avg
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View

from .models import Album, ArtistLabel, Band, Genre, Rating
from .forms import ReviewForm, RatingForm


class GenreYear:

    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Album.objects.filter(draft=False)

    def get_country(self):
        return Album.objects.order_by().values('country').distinct()


class AlbumView(GenreYear, ListView):
    model = Album
    queryset = Album.objects.filter(draft=False).distinct()
    paginate_by = 6


class AlbumDetailView(GenreYear, DetailView):
    model = Album
    slug_field = 'url'

    def get_user_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[-1].strip()
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['star_form'] = RatingForm()
        try:
            rating = Rating.objects.filter(ip=self.request.META.get('REMOTE_ADDR')).filter(album=self.model)
            context['user_rating'] = rating.get().star
        except:
            context['user_rating'] = None
        return context


class ArtistView(GenreYear, DetailView):
    model = ArtistLabel
    template_name = 'albums/artist.html'
    slug_field = 'name'


class BandView(DetailView):
    model = Band
    template_name = 'albums/band.html'
    slug_field = 'name'


class AddReview(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        album = Album.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get('parent', None):
                form.parent_id = int(request.POST.get('parent'))
            form.album = album
            form.save()
        return redirect(album.get_absolute_url())


class FilterAlbumsView(GenreYear, ListView):
    paginate_by = 6

    def get_queryset(self):
        queryset = Album.objects.filter(
            Q(year__in=self.request.GET.getlist('year')) |
            Q(country__in=self.request.GET.getlist('country')) |
            Q(genres__in=self.request.GET.getlist('genre'))
        ).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['year'] = ''.join([f"year={x}&" for x in self.request.GET.getlist('year')])
        context['country'] = ''.join([f"country={x}&" for x in self.request.GET.getlist('country')])
        context['genre'] = ''.join([f"genre={x}&" for x in self.request.GET.getlist('genre')])
        return context


class AddStarRating(View):
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                album_id=int(request.POST.get('album')),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class Search(ListView):
    paginate_by = 6

    def get_queryset(self):
        return Album.objects.filter(title__icontains=self.request.GET.get('q'))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = f"q={self.request.GET.get('q')}&"
        return context

templates/albums/album_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="left-ads-display col-lg-8">
    <div class="row">
        <div class="desc1-left col-md-6">
            <img src="{{ album.cover.url }}" class="img-fluid" alt="">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">
            <h3 class="editContent" style="outline: none; cursor: inherit;">
                {{ album.title }}</h3>
            <ul>
                <li style="list-style: none"><span><b>Группа:</b> {{ album.category }}</span></li>
                <li style="list-style: none"><span><b>Год:</b> {{ album.year }}</span></li>
                <li style="list-style: none"><span><b>Страна:</b> {{ album.country }}</span></li>
                <li style="list-style: none">
                    <span><b>Лейбл:</b>
                        {% for lable in album.label.all %}
                            <a href="{% url 'artist_detail' lable.name %}">{{ lable.name }}</a>,
                        {% endfor %}
                    </span>
                </li>
                <li style="list-style: none">
                    <span><b>Музыканты:</b>
                        {% for artist in album.artist.all %}
                            <a href="{% url 'artist_detail' artist.name %}">{{ artist.name }}</a>,
                        {% endfor %}
                    </span>
                </li>
                <li style="list-style: none">
                    <span><b>Жанр:</b> {% for genre in album.genres.all %}{{ genre }} {% endfor %}</span>
                </li>
                <li style="list-style: none">
                    <span><b>Дата выхода</b> {{ album.premiere }}</span>
                </li>
                <li style="list-style: none">
                    <span><b>Прослушиваний:</b> {{ album.streams }}</span>
                </li>
                <li style="list-style: none">
                    <form action="{% url 'add_rating' %}" method="post" name="rating">
                        {% csrf_token %}
                            <b>Ваша оценка:</b>
                        {% if user_rating %}
                            {{ user_rating }}
                        {% else %}
                            <input type="hidden" value="{{ album.id }}" name="album">
                            <span class="rating">
                                {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating{{ v }}" type="radio" name="star"
                                           value="{{ k }}">
                                    <label for="rating{{ v }}">{{ k }}</label>
                                {% endfor %}
                            </span>
                        {% endif %}
                    </form>
                </li>
                <li style="list-style: none">
                    <span class="rating_all">
                        <ul class="stars">
                            <b class="mr-2">Общий рейтинг:</b>
                            <i class="fa fa-star{% if album.average_rating == 0.5 %}-half-o{% elif album.average_rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if album.average_rating == 1.5 %}-half-o{% elif album.average_rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if album.average_rating == 2.5 %}-half-o{% elif album.average_rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if album.average_rating == 3.5 %}-half-o{% elif album.average_rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if album.average_rating == 4.5 %}-half-o{% elif album.average_rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                        </ul>
                    </span>
                </li>
            </ul>
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">
        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
            Об альбоме {{ album.category }}: {{ album.title }}</h3><br>
        <p>
            {% for image in album.images_set.all %}
                <img src="{{ image.image.url }}" class="img-fluid img-albums-covers" alt="{{ image.title }}">
            {% endfor %}
        </p>
        <p class="editContent" style="outline: none; cursor: inherit;">
            {{ album.description | safe }}
        </p>
    </div>
    <hr>
    <div class="row">
        <div class="single-form-left">
            <div class="contact-single">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    <p class="text-sm-start">Отзывов: {{ album.reviews_set.count }}</p>
                    <span class="sub-tittle editContent" style="outline: none; cursor: inherit;"></span>Оставить отзыв
                </h3>
                <form action="{% url 'add_review' album.id %}" method="post" class="mt-4" id="formReview">
                    {% csrf_token %}
                    <input type="hidden" name="parent" id="contactparent" value="">
                    <div class="form-group editContent" style="outline: none; cursor: inherit;">
                        <label for="contactcomment" class="editContent">
                            Ваш комментарий *
                        </label>
                        <textarea class="form-control border" rows="5" id="contactcomment" required="" name="text"></textarea>
                    </div>
                    <div class="d-sm-flex">
                        <div class="col-sm-6 form-group p-0 editContent" style="outline: none; cursor: inherit;">
                            <label for="contactusername" class="editContent">
                                Имя *
                            </label>
                            <input type="text" class="form-control border" id="contactusername" required="" name="name">
                        </div>
                        <div class="col-sm-6 form-group ml-sm-3 editContent">
                            <label for="contactemail" class="editContent" style="outline: none; cursor: inherit;">
                                Email *
                            </label>
                            <input type="email" class="form-control border" id="contactemail" required="" name="email">
                        </div>
                    </div>
                    <button type="submit" class="mt-3 btn btn-success btn-block py-3" style="outline: none; cursor: inherit;">Отправить</button>
                </form>
            </div>
        </div>
    </div>
    <div>
        {% for review in album.get_review %}
            <div class="media py-5">
                <img src="{% static 'default_images/default-avatar.jpg' %}" class="mr-3 img-fluid avatar_image" alt="image">
                <div class="media-body mt-3">
                    <h5 class="mt-0 editContent">{{ review.name }}</h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
                    {% for answer in review.reviews_set.all %}
                    <div class="media mt-5 editContent">
                            <img src="{% static 'default_images/default-avatar.jpg' %}" class="mr-3 img-fluid avatar_image" alt="image">
                        <div class="media-body mt-3">
                            <h5 class="mt-0 editContent">{{ answer.name }}</h5>
                            <p class="mt-2 editContent">{{ answer.text }} </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>
<script>
    function addReview(name, id){
        document.getElementById('contactparent').value = id;
        document.getElementById('contactcomment').innerText = `${name}, `;
    }
</script>
{% endblock %}

templates/albums/album_list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{%  for album in album_list %}
    <div class="col-md-4 product-men">
        <div class="product-shoe-info editContent text-center mt-lg-4" >
            <div class="men-thumb-item">
                <a href="{% url 'album_detail' album.url %}">
                    <img src="{{ album.cover.url }}" class="img-fluid" alt="" >
                </a>
            </div>
            <div class="item-info-product">
                <h4 class="">
                    <a href="{% url 'album_detail' album.url %}" class="editContent" >{{ album.title }}</a>
                </h4>
                <div class="product_price">
                    <div class="grid-price ">
                        <a href="{% url 'band_detail' album.category.name %}"><span class="money editContent" >{{ album.category.name }}</span></a>
                    </div>
                </div>
                <ul class="stars mt-3">
                    <i class="fa fa-star{% if album.average_rating == 0.5 %}-half-o{% elif album.average_rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if album.average_rating == 1.5 %}-half-o{% elif album.average_rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if album.average_rating == 2.5 %}-half-o{% elif album.average_rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if album.average_rating == 3.5 %}-half-o{% elif album.average_rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if album.average_rating == 4.5 %}-half-o{% elif album.average_rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                </ul>
            </div>
        </div>
    </div>
{% endfor %}

{% endblock %}

templates/albums/artist.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="left-ads-display col-lg-8">
    <div class="row">
        <div class="desc1-left col-md-6">
            <img src="{{ artistlabel.image.url }}" class="img-fluid" alt="">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">
            <h3 class="editContent">
                {{ artistlabel.title }}
            </h3>
            <h5 class="editContent"></h5>
            <ul>
                {% if artistlabel.age %}
                <li>
                    <span><b>Возраст:</b> {{ artistlabel.age }}</span>
                </li>
                {% endif %}
                {% if artistlabel.album_artist.all %}
                <li>
                    <span><b>Выпустил альбомы:</b>
                        {% for album in artistlabel.album_artist.all %}
                            <a href="{% url 'album_detail' album.url %}">{{ album.title }}</a>,
                        {% endfor %}
                    </span>
                </li>
                {% endif %}
                {% if artistlabel.album_label.all %}
                <li>
                    <span><b>Выпустил альбомы:</b>
                        {% for album in artistlabel.album_label.all %}
                            <a href="{% url 'album_detail' album.url %}">{{ album.title }}</a>,
                        {% endfor %}
                    </span>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">
        <h3 class="shop-sing editContent">
            {{ artistlabel.name }}
        </h3>
        <p class="editContent">
            {{ artistlabel.description|safe }}
        </p>
    </div>
</div>
{% endblock %}

templates/albums/band.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="left-ads-display col-lg-8">
    <div class="row sub-para-w3layouts mt-5">
        <h3 class="shop-sing editContent">
            {{ band.name }}
        </h3>
        <p class="editContent">
            {{ band.description|safe }}
        </p>
    </div>
</div>
<div class="left-ads-display col-lg-9">
    <div class="row">
       {% for album in band.get_albums %}
            <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4" >
                        <div class="men-thumb-item">
                            <a href="{% url 'album_detail' album.url %}">
                                <img src="{{ album.cover.url }}" class="img-fluid" alt="" >
                            </a>
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{% url 'album_detail' album.url %}" class="editContent" >{{ album.title }}</a>
                            </h4>
                        </div>
                    </div>
            </div>
       {% endfor %}
    </div>
</div>
{% endblock %}